config/routes.rb
Rails.application.routes.draw do

  root to: "pages#home"

  devise_for :users
  resources :products

  resource :cart, only: :show
  resources :cart_items, only: [:create, :update, :destroy]
  resources :orders, only: [:new, :create, :show]

  get 'promotions', to: 'products#promotions'
  get 'about', to: 'pages#about'
  get 'legales', to: 'pages#legales'


  get 'contact', to: 'pages#contact'
  post 'contact', to: 'pages#contact'
end

app/views/shared/_cart_preview.html.erb
<div class="offcanvas offcanvas-start" data-bs-backdrop="static" tabindex="-1" id="staticBackdrop2" aria-labelledby="staticBackdropLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="staticBackdropLabel">Offcanvas</h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    <div>
      I will not close if you click outside of me.







    </div>
  </div>
</div>

app/views/shared/_contact_form.html.erb
<div id="contacto" class="container mt-5">
  <div class="row">
    <div class="col-md-5 mx-auto">
      <h2 class="mb-4"><strong>Contacto</strong></h2>
      <h4 class="mb-4">¿Tenés una consulta? Escribinos.</h4>
      <%= form_with url: contact_path, local: true, html: { multipart: true } do |form| %>
        <div class="form-group">
          <%= form.label :name, 'Nombre y Apellido' %>
          <%= form.text_field :name, class: 'form-control input-line-contact' %>
        </div>
        <div class="form-group">
          <%= form.label :email, 'Correo Electrónico' %>
          <%= form.email_field :email, class: 'form-control input-line-contact' %>
        </div>
        <div class="form-group">
          <%= form.label :phone, 'Número de Teléfono' %>
          <%= form.text_field :phone, class: 'form-control input-line-contact' %>
        </div>
        <div class="form-group">
          <%= form.label :message, 'Mensaje' %>
          <%= form.text_area :message, class: 'form-control input-line-contact' %>
        </div>
        <div class="form-group">
          <%= form.label :attachment, 'Adjuntar Archivo (opcional)' %>
          <%= form.file_field :attachment, class: 'form-control input-line-contact' %>
        </div>
        <div class="form-group mt-3">
          <%= form.submit 'Enviar', class: 'btn btn-primary btn-lg btn-custom w-100 mb-5 rounded-5' %>
        </div>
      <% end %>
    </div>

    <div class="col-md-4 mx-auto my-auto">
      <div class="card p-2 rounded-5" style="background-color: #E1E4E3; min-width: 336px;">
        <div class="card-body text-center">
          <h4 class="card-title mb-0 fw-bold text-primary">Casa central:</h4>
          <p class="card-text mt-0">
            Rambla República de México 5863<br>
            Montevideo
          </p>
          <h4 class="card-title mt-3 mb-0 fw-bold text-primary">Sucursal Maldonado:</h4>
          <p class="card-text mt-0">
            Calle Av. España, Parada 26
          </p>
          <p class="card-text">
            Lun - Vie 9:00 - 18:00<br>
            Sábados 9:00 - 13:00
          </p>
          <div class="card-text">
            <i class="fa-solid fa-phone-volume"></i>
            <strong class="fs-2">0800 8000</strong>
          </div>
          <div class="card-text">
            <%= link_to "https://wa.me/+59895054348", target: "_blank", rel: "noopener" do %>
              <i class="fab fa-whatsapp fa-lg"></i> Escribinos por WhatsApp
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
document.addEventListener("DOMContentLoaded", function () {
  // Selecciona todos los enlaces con la clase 'no-focus'
  const links = document.querySelectorAll('a.no-focus');

  links.forEach(link => {
    link.addEventListener('click', function (event) {
      event.preventDefault(); // Evita el comportamiento predeterminado
      window.open(this.href, '_blank', 'noopener,noreferrer'); // Abre el enlace en una nueva pestaña
    });
  });
});
</script>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert" style="white-space: pre-line;">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="bg-primary mt-4">
  <div class="container py-5 ps-4">
    <div class="row">
      <!-- Primera Columna -->
      <div class="col-md-5 col-sm-12">
        <p class="my-1 fw-bold" style="font-size: 1.2rem;">Motor con 1 año de garantía por defectos de fábrica.</p>
        <p class="my-1 fw-bold" style="font-size: 1.2rem;">Instalación incluida en Montevideo y alrededores.</p>
        <p class="mt-1 fw-bold mb-4" style="font-size: 1.2rem;">Envíos al interior a cargo del comprador.</p>
        <%= link_to 'Términos y condiciones', legales_path, class: 'linkfooter my-5 fw-bold', style: "font-size: 1.2rem;" %>
      </div>

      <!-- Espacio vacío (columna separadora en pantallas grandes) -->
      <div class="col-md-1 d-none d-md-block"></div>

      <!-- Segunda Columna (oculta por ahora) -->
      <div class="col-md-3 d-none d-md-block"></div>

      <!-- Cuarta Columna (Logos) -->
      <div class="col-md-3 col-sm-12 text-center">
        <%= image_tag('Logo-PPA.png', alt: 'Logo PPA', class: 'img-fluid mb-3 mt-3 footer-logos') %>
        <br>
        <%= image_tag('sicher-logo.png', alt: 'Logo Sicher', class: 'img-fluid footer-logos') %>
      </div>
    </div>
  </div>

  <!-- Subfooter -->
  <div class="subfooter w-100">
    <div class="d-flex flex-column flex-md-row justify-content-between align-items-center my-2 p-3">
      <!-- Usuario logueado -->
      <div class="ms-3 mb-3 mb-md-0 text-center text-md-start">
        <% if user_signed_in? %>
          <p class="mb-0" style="font-size: 1rem;">
            Sesión iniciada: <%= current_user.email %>
            <br>
            <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete, class: "btn btn-link text-dark p-0" %>
          </p>
        <% end %>
      </div>

      <!-- Redes Sociales -->
      <div class="d-flex justify-content-center align-items-center">
        <p class="mb-0 me-3" style="font-size: 1.4rem;">Síguenos en:</p>
        <%= link_to 'https://www.instagram.com/ppauruguay/?hl=es', target: '_blank', class: 'text-black me-2' do %>
          <i class="fa-brands fa-instagram fa-2x"></i>
        <% end %>
        <%= link_to 'https://www.facebook.com/profile.php?id=100064102380858', target: '_blank', class: 'text-black me-2' do %>
          <i class="fa-brands fa-facebook-f fa-2x"></i>
        <% end %>
        <%= link_to 'https://www.tiktok.com/@ppa.uruguay.sicher?_t=ZM-8sBYDBXWJuv&_r=1', target: '_blank', class: 'text-black me-2' do %>
          <i class="fa-brands fa-tiktok fa-2x"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_map.html.erb
<div class="col-12 mx-2 mt-5 mb-1">
  <div id="map"></div>
</div>

<script async
  src="https://maps.googleapis.com/maps/api/js?key=<%= @google_api_key %>&callback=initMap">
  // !!!!!!!!!!REEMPLAZAR CAMBIAR POR API KEY DEL DUEÑO!!!!!!!!!!!!!
</script>

<script>
  function initMap() {
    var location = {lat: -34.8978457839486, lng: -56.069537488069656};
    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 16,
      center: location
    });
    var marker = new google.maps.Marker({
      position: location,
      map: map
    });
  }
</script>

app/views/shared/_navbar.html.erb
<div class="fixed-top">
  <!-- Primera fila del navbar -->
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon mb-0">
    <div class="container-fluid">
      <div class="cat1 d-flex align-items-center">
        <%= link_to root_path, class: "navbar-brand me-1" do %>
          <%= image_tag("Logo-PPA.png", alt: "Logo PPA", class: "navbar-logo") %>
        <% end %>

        <!-- Barra de búsqueda -->
        <div class="cat2 d-none d-lg-flex mx-3">
          <%= form_with url: products_path, method: :get, local: true, class: "form-inline my-2 my-lg-0" do |form| %>
            <div class="input-group">
              <%= form.text_field :query, value: params[:query], class: "form-control custom-width", placeholder: "Buscar productos", style: "border-radius: 10px 0 0 10px;" %>
              <div class="input-group-append">
                <button type="submit" class="btn btn-outline-primary" style="border-radius: 0 10px 10px 0;">
                  <i class="fas fa-search"></i>
                </button>
              </div>
            </div>
          <% end %>
        </div>

        <%= link_to root_path, class: "navbar-brand ms-1" do %>
          <%= image_tag("sicher-logo.png", alt: "Logo Sicher", class: "navbar-logo") %>
        <% end %>
      </div>

      <!-- Íconos de la derecha -->
      <div class="cat3 d-flex">
        <ul class="navbar-nav ms-auto d-flex align-items-center" style="font-size: 1.6rem;">
          <li class="nav-item">
            <%= link_to "https://wa.me/+59895054348", class: "nav-link", target: "_blank", rel: "noopener" do %>
              <i class="fab fa-whatsapp fa-lg" style="color: #23D366;"></i>
            <% end %>
          </li>
          </li>
          <li class="nav-item position-relative">
            <%= link_to cart_path, class: "nav-link position-relative" do %>
              <i class="fas fa-shopping-cart fa-lg text-primary"></i>
              <% if @cart_items_count > 0 %>
                <span class="position-absolute top-10 start-100 translate-middle badge rounded-pill bg-primary">
                  <%= @cart_items_count %>
                </span>
              <% end %>
            <% end %>
          </li>
          <!-- Botón de menú dropdown para móviles -->
          <li class="nav-item d-lg-none">
            <button class="btn nav-link nav-link-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
              <i class="fa-solid fa-bars fa-lg text-primary"></i>
            </button>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Segunda fila del navbar -->
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon mt-0 pt-0" style="border-bottom: 1px solid #dee2e6;">
    <div class="container-fluid justify-content-center">
      <!-- Navbar inferior (visible en pantallas grandes) -->
      <div class="cat4 d-none d-lg-flex w-100 justify-content-center">
        <ul class="navbar-nav justify-content-between w-50" style="font-size: 1.4rem;">
          <li class="nav-item">
            <%= link_to "Nosotros", about_path, class: "nav-link text-black fw-bold" %>
          </li>
          <li class="nav-item dropdown position-relative">
            <a class="nav-link dropdown-toggle text-black fw-bold" href="#" id="storeDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" data-bs-auto-close="outside">
              Tienda
            </a>
            <ul class="dropdown-menu" aria-labelledby="storeDropdown">
              <li><%= link_to "Todos", products_path, class: "dropdown-item text-white" %></li>
              <li class="dropdown dropend position-relative">
                <a class="dropdown-item dropdown-toggle text-white" href="#" id="automatismosDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" data-bs-auto-close="outside">
                  Automatismos
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Corredizos", products_path(query: "Corredizo"), class: "dropdown-item text-white" %></li>
                  <li><%= link_to "Basculantes", products_path(query: "Basculante"), class: "dropdown-item text-white" %></li>
                  <li><%= link_to "Pivotantes", products_path(query: "Pivotante"), class: "dropdown-item text-white" %></li>
                </ul>
              </li>
            </ul>
          </li>
          <li class="nav-item">
            <%= link_to "Promociones", promotions_path, class: "nav-link text-black fw-bold" %>
          </li>
          <li class="nav-item">
            <%= link_to "Contacto", contact_path, class: "nav-link text-black fw-bold" %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

<!-- Offcanvas para móviles -->
<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Menú</h5>
    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Cerrar"></button>
  </div>
  <div class="offcanvas-body">
    <!-- Barra de búsqueda dentro del dropdown -->
    <div class="mb-3">
      <%= form_with url: products_path, method: :get, local: true, class: "form-inline my-2 my-lg-0" do |form| %>
        <div class="input-group">
          <%= form.text_field :query, value: params[:query], class: "form-control custom-width", placeholder: "Buscar productos", style: "border-radius: 10px 0 0 10px;" %>
          <div class="input-group-append">
            <button type="submit" class="btn btn-outline-primary" style="border-radius: 0 10px 10px 0;">
              <i class="fas fa-search"></i>
            </button>
          </div>
        </div>
      <% end %>
    </div>
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to "Nosotros", about_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Promociones", promotions_path, class: "nav-link" %>
      </li>
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="storeDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" data-bs-auto-close="outside">
    Tienda
  </a>
  <ul class="dropdown-menu" aria-labelledby="storeDropdown">
    <li><%= link_to "Todos", products_path, class: "dropdown-item" %></li>
    <li class="dropdown dropend">
      <a class="dropdown-item dropdown-toggle" href="#" id="automatismosDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" data-bs-auto-close="outside">
        Automatismos
      </a>
      <ul class="dropdown-menu">
        <li><%= link_to "Corredizos", products_path(query: "Corredizo"), class: "dropdown-item" %></li>
        <li><%= link_to "Basculantes", products_path(query: "Basculante"), class: "dropdown-item" %></li>
        <li><%= link_to "Pivotantes", products_path(query: "Pivotante"), class: "dropdown-item" %></li>
      </ul>
    </li>
  </ul>
</li>
      <li class="nav-item">
        <%= link_to "Contacto", contact_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</div>

<%# ok por ahora mejorcito %>