config/routes.rb
Rails.application.routes.draw do

  root to: "pages#home"

  devise_for :users
  resources :products

  resource :cart, only: :show
  resources :cart_items, only: [:create, :update, :destroy]
  resources :orders, only: [:new, :create, :show]

  get 'promotions', to: 'products#promotions'
  get 'about', to: 'pages#about'
  get 'legales', to: 'pages#legales'


  get 'contact', to: 'pages#contact'
  post 'contact', to: 'pages#contact'
end

app/models/product.rb
class Product < ApplicationRecord
  include ActionView::Helpers::NumberHelper

  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy

  has_many_attached :photos

  validates :name, :price, :category, :subcategory, presence: true
  validate :at_least_one_photo

  validates :price, numericality: { greater_than: 0 }, allow_nil: false
  validates :controls_included, :rack_meters, :arms, numericality: { only_integer: true, allow_nil: true }
  validates :installation_included, inclusion: { in: [true, false], message: "debe ser Sí o No" }
  validates :promotional_price, numericality: { greater_than: 0 }, allow_nil: true
  validates :discount_percentage, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }, allow_nil: true

  validates :promo_text, length: { maximum: 200 }, allow_blank: true
  validate :promo_text_line_limit

  before_save :calculate_discount_percentage, if: :on_sale?

  def promo_text_line_limit
    if promo_text.present? && promo_text.lines.count > 5
      errors.add(:promo_text, "No puede tener más de 5 líneas.")
    end
  end

  def on_sale?
    on_sale && promotional_price.present?
  end

  def calculate_discount_percentage
    if promotional_price.present? && price.present? && promotional_price > 0
      self.discount_percentage = ((1 - promotional_price.to_f / price.to_f) * 100)
    else
      self.discount_percentage = nil
    end
  end

  def current_price
    on_sale? ? promotional_price : price
  end

  def formatted_price
    number_with_delimiter(price, delimiter: '.', separator: '')
  end

  def formatted_promotional_price
    number_with_delimiter(promotional_price, delimiter: '.', separator: '')
  end

  def formatted_discount_percentage
    discount_percentage&.round || 0
  end

  def at_least_one_photo
    errors.add(:photos, "debe incluir al menos una foto") if photos.blank?
  end

  def warranty_description
    if installation_included
      "* Garantía 1 Año. Cubre defectos de fábrica. Repuestos y Servicio Técnico."
    else
      "* Garantía 1 Año. No cubre garantía por mala instalación."
    end
  end

  include PgSearch::Model
  pg_search_scope :search_by,
                  against: %i[name details category subcategory installation_included promo_text product_type],
                  using: { tsearch: { prefix: true } }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @products = Product.all
    @products = @products.where(category: params[:category]) if params[:category].present?
    @products = @products.where(subcategory: params[:subcategory]) if params[:subcategory].present?
    @products = @products.search_by(params[:query]) if params[:query].present?
  end

  def show
    @product = Product.find(params[:id])
    @related_products = Product.where(subcategory: @product.subcategory).where.not(id: @product.id).limit(5)
  end

  def new
    @product = Product.new
    authorize @product
  end

  def create
    @product = Product.new(product_params)
    authorize @product

    if @product.save
      redirect_to @product, notice: 'Producto creado con éxito.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @product = Product.find(params[:id])
    authorize @product
  end

  def update
    @product = Product.find(params[:id])
    authorize @product

    if params[:remove_photos].present?
      params[:remove_photos].each { |photo_id| @product.photos.find(photo_id).purge }
    end

    @product.photos.attach(product_params[:photos]) if product_params[:photos].present?

    if @product.update(product_params.except(:photos))
      redirect_to @product, notice: 'Producto actualizado con éxito.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product = Product.find(params[:id])
    authorize @product
    @product.destroy
    redirect_to products_url, notice: 'Producto eliminado con éxito.'
  end

  def promotions
    @promoted_products = Product.where(on_sale: true)
  end

  private

  def product_params
    params.require(:product).permit(
      :name, :price, :category, :subcategory, :details, :stock, :promo_text,
      :on_sale, :discount_percentage, :promotional_price,
      :sku, :warranty, :power, :controls_included, :rack_meters,
      :arms, :usage_type, :gate_max_length, :indication, :installation_included,
      photos: []
    )
  end
end

app/views/products/_product_card.html.erb
<div class="col">
  <div class="card productcard h-100 mb-0 rounded-5" style="background-color: #E1E4E3;">
    <% if product.photos.present? %>
      <div class="position-relative d-flex justify-content-center align-items-center">
        <%= link_to product_path(product) do %>
          <%= cl_image_tag(product.photos.first.key, class: "card-img-top p-3 rounded-50", crop: :thumb, alt: product.name) %>
        <% end %>
        <% if product.on_sale? %>
          <div class="position-absolute" style="bottom: 20%; left: 25px; z-index: 1; width: 50px; height: 50px;">
            <%= image_tag('fire3.png', class: 'img-fluid') %>
          </div>
        <% end %>
        <% if product.installation_included %>
          <div class="position-absolute bg-danger text-center fw-bold text-white px-2 py-1 rounded-pill text-wrap" style="top: 12%; right: 9%; max-width: 80px; font-size: 0.75rem;">
            Instalación incluida
          </div>
        <% else %>
          <div class="position-absolute text-center text-white px-2 py-1 rounded-pill text-wrap fw-bold" style="top: 12%; right: 9%; max-width: 80px; font-size: 0.75rem; background-color: #fbab10;">

            Sin instalación
          </div>
        <% end %>
      </div>
    <% end %>
    <div class="card-body d-flex flex-column text-center">

      <h4 class="card-title fw-bolder"><%= link_to product.name, product %></h4>

      <div class="mt-auto">
        <% if product.on_sale? %>
          <p class="text-decoration-line-through text-muted mb-0 text-secondary">
            Precio: $ <%= product.formatted_price %>
          </p>
          <p class="mt-0">
            <strong>Precio en oferta:</strong> $ <%= product.formatted_promotional_price %> Imp. Inc.
          </p>
        <% else %>
          <p class="highlighted-text">$ <%= product.formatted_price %> Imp. Inc.</p>
        <% end %>
      </div>

      <p class="my-0 text-secondary">Potencia: <%= product.power %></p>
      <p class="my-0 text-secondary">Controles incluidos: <%= product.controls_included %></p>
      <p class="my-0 text-secondary">Uso: <%= product.usage_type %></p>
      <p class="mt-0 mb-3 text-secondary">Garantía: <%= product.warranty %></p>

      <div class="d-flex justify-content-center mt-2">
        <%= button_to cart_items_path(product_id: product.id, quantity: 1), method: :post, class: "btn btn-custom btn-primary ms-3 rounded-5" do %>
          Agregar al Carrito
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/products/_product_card_promo.html.erb
<div class="promo-card-container promo-card-large d-flex justify-content-center">
  <div class="promo-card">
    <div class="card h-100 py-4 flex-row rounded-5" style="background-color: #E1E4E3 !important;">
      <% if product.photos.present? %>
        <div class="position-relative ms-5 d-flex justify-content-center align-items-center" style="flex: 1;">
          <%= link_to product_path(product) do %>
            <%= cl_image_tag(product.photos.first.key, class: "card-img rounded-50", height: 200, width: 200, crop: :thumb, alt: product.name) %>
          <% end %>
          <% if product.on_sale? %>
            <div class="fire-icon">
              <%= image_tag('fire3.png', class: 'img-fluid') %>
            </div>
          <% end %>
          <% if product.installation_included %>
            <div class="position-absolute bg-danger text-center text-white px-2 py-1 rounded-pill text-wrap" style="top: 12%; right: 2%; max-width: 80px; font-size: 0.75rem;">
              Instalación incluida
            </div>
          <% else %>
            <div class="position-absolute text-center text-white px-2 py-1 rounded-pill text-wrap fw-bold" style="top: 12%; right: 2%; max-width: 80px; font-size: 0.75rem; background-color: #fbab10;">

              Sin instalación
            </div>
          <% end %>
        </div>
      <% end %>
      <div class="card-body d-flex flex-column text-center" style="flex: 2;">
        <% if product.on_sale? %>
          <p class="mb-3 mx-auto text-white px-5 p-2 fw-bold rounded-pill discount-tag" style="font-size: 1.05rem;">
            DESCUENTO: <%= product.discount_percentage %> %
          </p>
        <% end %>

        <h5 class="card-title"><strong><%= link_to product.name, product %></strong></h5>

        <p class="card-text text-secondary mt-2 promo-card-text"><%= product.promo_text %></p>
        <div class="mt-auto">
          <% if product.on_sale? %>
            <p class="text-decoration-line-through text-muted mb-0">Precio: $ <%= product.formatted_price %></p>
            <p class="my-0"><strong>Precio en oferta:</strong> $ <%= product.formatted_promotional_price %></p>
            <p class="mt-0">Imp. Inc.</p>
          <% else %>
            <p><strong>Precio:</strong> $ <%= product.formatted_price %></p>
          <% end %>
          <div class="d-flex justify-content-center mt-2">
            <%= button_to cart_items_path(product_id: product.id, quantity: 1), method: :post, class: "btn btn-custom btn-primary ms-3 rounded-5", style: "width: 175px; margin: 0 auto;" do %>
              <i class="fa-solid fa-cart-plus pe-3"></i> Agregar
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%# original %>



<div class="promo-card-container promo-card-small ">
  <div class="promo-card ">
    <div class="card flex-column align-items-center justify-content-center rounded-5">
      <% if product.photos.present? %>
        <div class="promo-card-image-container mt-5">
          <%= link_to product_path(product) do %>
            <%= cl_image_tag(
            product.photos.first.key,
            class: "promo-card-image",
            alt: product.name,
            width: 300,
            height: 300,
            crop: :fill
          ) %>
          <% end %>
          <% if product.on_sale? %>
            <div class="fire-icon">
              <%= image_tag('fire3.png', class: 'img-fluid') %>
            </div>
          <% end %>
          <% if product.installation_included %>
            <div class="promo-card-badge bg-danger">
              Instalación incluida
            </div>
          <% else %>
            <div class="promo-card-badge fw-bold" style="background-color: #fbab10;">
              Sin instalación
            </div>
          <% end %>
        </div>
      <% end %>

      <div class="promo-card-body text-center">
        <% if product.on_sale? %>
          <p class="discount-tag mt-3 fw-bold">
            DESCUENTO: <%= product.discount_percentage.to_i %> %
          </p>
        <% end %>
        <h5 class="card-title"><%= link_to product.name, product %></h5>
        <p class="card-text text-secondary mt-2 promo-card-text"><%= product.promo_text %></p>
        <div>
          <% if product.on_sale? %>
            <p class="text-decoration-line-through text-muted mb-0">Precio: $ <%= product.formatted_price %></p>
            <p><strong>Precio en oferta:</strong> $ <%= product.formatted_promotional_price %></p>
          <% else %>
            <p><strong>Precio:</strong> $ <%= product.formatted_price %></p>
          <% end %>
          <%= button_to cart_items_path(product_id: product.id, quantity: 1), method: :post, class: "btn btn-primary mt-3 mb-5 rounded-5 promo-card-button" do %>
            <i class="fa-solid fa-cart-plus pe-3"></i> Agregar
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<%# la nueva para pantallas chicas %>

app/views/products/edit.html.erb
<!-- app/views/products/edit.html.erb -->
<h1 class="mt-3" style="text-align: center;">Editar Producto</h1>

<%= render 'form', product: @product %>

app/views/products/index.html.erb
<div class="container">
  <h2 class="mt-5 fw-bold">Lista de Productos</h2>

  <% if user_signed_in? && policy(Product).create? %>
    <div class="d-flex justify-content-end mb-3">
      <%= link_to "Nuevo Producto", new_product_path, class: "btn btn-primary text-white" %>
    </div>
  <% end %>

  <%# <div class="row row-cols-1 row-cols-md-2 row-cols-lg-4 g-4"> %>
  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-4">
    <% @products.each do |product| %>
      <%= render partial: 'products/product_card', locals: { product: product } %>
    <% end %>
  </div>

  <% if @products.empty? %>
    <p class="fst-italic">No se encontraron productos.</p>
  <% end %>
</div>

app/views/products/new.html.erb
<!-- app/views/products/new.html.erb -->
<h1 class="mt-3" style="text-align: center;">Nuevo Producto</h1>


<%= render 'form', product: @product %>

app/views/products/promotions.html.erb
<div class="container">
  <h2 class="my-5 fw-bold text-center">Promociones</h2>


  <% if @promoted_products.present? %>
    <div class="">
      <% @promoted_products.each do |product| %>
          <%= render partial: 'product_card_promo', locals: { product: product } %>
      <% end %>
    </div>
  <% else %>
    <p>"No hay promociones en este momento".</p>
  <% end %>
</div>

app/views/products/show.html.erb
<div class="container mt-5">

  <p class="mb-5" style="font-size: 1.25rem;">
    <%= link_to "Tienda", products_path %> /
    <%= link_to @product.category, products_path(category: @product.category) %> /
    <%= link_to @product.subcategory, products_path(category: @product.category, subcategory: @product.subcategory) %>
  </p>

  <div class="row">
    <div class="col-12 d-md-none text-center">
      <h1 class="product-name"><%= @product.name %></h1>
    </div>

    <div class="col-12 col-md-6 position-relative">
      <!-- Imagen principal del producto -->
      <div class="text-center">
        <% if @product.photos.present? %>
          <div class="main-image-container">
            <%= cl_image_tag(@product.photos.first.key, id: "main-image", height: 600, width: 800, crop: :fill, class: "img-fluid border") %>
          </div>
        <% end %>
      </div>

      <!-- Con o Sin Instalación -->
      <% if @product.installation_included %>
        <div class="position-absolute bg-danger text-center text-white px-2 py-1 rounded-pill text-wrap" style="top: -5%; right: 0%; max-width: 120px; font-size: 1.2rem;">
          Instalación incluida
        </div>
      <% else %>
        <div class="position-absolute text-center text-white px-2 py-1 rounded-pill text-wrap" style="top: -5%; right: -5%; max-width: 120px; font-size: 1.2rem; background-color: #fbab10;">
          Sin instalación
        </div>
      <% end %>

      <!-- Miniaturas -->
      <% if @product.photos.length > 1 %>
        <div id="thumbnailCarousel" class="carousel slide mt-3" data-bs-ride="false">
          <div class="carousel-inner">
            <% @product.photos.each_slice(4).with_index do |photos_slice, index| %>
              <div class="carousel-item <%= 'active' if index == 0 %>">
                <div class="row">
                  <% photos_slice.each do |photo| %>
                  <div class="col-3">
                    <%= link_to(cl_image_tag(photo.key, height: 150, width: 200, crop: :fill, class: "img-thumbnail img-fluid"), "#", onclick: "document.getElementById('main-image').src=this.querySelector('img').src.replace('h_150,w_200', 'h_600,w_800'); return false;") %>
                  </div>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
          <% if @product.photos.length > 4 %>
            <a class="carousel-control-prev custom-carousel-control" href="#thumbnailCarousel" role="button" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </a>
            <a class="carousel-control-next custom-carousel-control" href="#thumbnailCarousel" role="button" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </a>
          <% end %>
        </div>
      <% end %>

      <!-- Botones de navegación -->
      <div class="d-flex justify-content-between align-items-center mt-1 mb-5">
        <div>
          <%= link_to 'Volver a Productos', products_path, class: 'btn btn-secondary rounded-5' %>
        </div>

        <% if user_signed_in? && policy(Product).create? %>
          <div class="d-flex gap-2">
            <%= link_to "Editar", edit_product_path(@product), class: "btn btn-secondary" if policy(@product).update? %>
            <%= link_to 'Eliminar', product_path(@product),
                  data: { turbo_method: :delete, turbo_confirm: '¿Estás seguro?' },
                  class: "btn btn-danger" if policy(@product).destroy? %>
          </div>
        <% end %>
      </div>
    </div>

    <!-- Información del producto -->
    <div class="col-12 col-md-5 ms-5 ps-5">

      <h1 class="d-none d-md-block"> Motor <strong><%= @product.name %></strong></h1>
      <p><strong>Categoría:</strong> <%= @product.category %> - <%= @product.subcategory %></p>

      <hr class="col-12 d-md-none">
      <% if @product.on_sale? %>
        <h3 class="text-decoration-line-through text-muted mb-0">Precio: $ <%= @product.formatted_price %></h3>
        <h3 class="mt-0 fw-bolder"><strong>Precio en oferta:</strong> $ <%= @product.formatted_promotional_price %> Imp. Inc.</h3>
      <% else %>
        <h3><strong>$ <%= @product.formatted_price %></strong> Imp. Inc.</h3>
      <% end %>

      <div class=" d-flex align-items-center my-5">
        <div class="input-group quantity-selector" style="width: auto;">
          <button class="btn btn-outline-secondary" type="button" id="button-decrement">-</button>
          <input type="text" class="form-control text-center" id="quantity-input" name="quantity" value="1" min="1" max="<%= @product.stock %>" readonly style="width: 60px;">
          <button class="btn btn-outline-secondary" type="button" id="button-increment">+</button>
        </div>
        <%= button_to cart_items_path(product_id: @product.id), method: :post, class: "btn btn-custom btn-primary ms-3 rounded-5", data: { turbo: false } do %>
          <i class="fa-solid fa-cart-plus"></i> Agregar al Carrito
        <% end %>
      </div>

      <p class="my-0 text-secondary">Potencia: <%= @product.power %></p>
      <p class="my-0 text-secondary">Controles incluidos: <%= @product.controls_included %></p>
      <p class="my-0 text-secondary">Uso: <%= @product.usage_type %></p>
      <p class="mt-0 mb-3 text-secondary">Garantía: <%= @product.warranty %></p>
      <% if @product.installation_included %>
       <p class="my-0 fw-bold"> Instalación incluida </p>
      <% else %>
       <p class="my-0 fw-bold"> Sin instalación </p>
      <% end %>
      <p class="mt-0 text-secondary">Disponible para retiro</p>

      <% if @product.details.present? %>
        <p><strong>Detalles:</strong> <%= @product.details %></p>
      <% end %>

      <% if @product.sku.present? %>
        <p><strong>SKU:</strong> <%= @product.sku %></p>
      <% end %>

      <% if @product.indication.present? %>
        <p><strong>Indicación:</strong> <%= @product.indication %></p>
      <% end %>

      <% if @product.stock.present? %>
        <p><strong>Stock:</strong> <%= @product.stock %></p>
      <% end %>
    </div>
  </div>

  <!-- Especificaciones -->
  <h3 class="fw-bold mt-5 text-center">Especificaciones:</h3>
  <div class="d-flex justify-content-center">
    <table class="table table-bordered mt-3 w-50">
      <tbody>
        <% if @product.power.present? %>
          <tr>
            <th>Potencia</th>
            <td><%= @product.power %></td>
          </tr>
        <% end %>
        <% if @product.controls_included.present? %>
          <tr>
            <th>Controles incluidos</th>
            <td><%= @product.controls_included %> controles</td>
          </tr>
        <% end %>
        <% if @product.rack_meters.present? %>
          <tr>
            <th>Metros de cremallera</th>
            <td><%= @product.rack_meters %> metros</td>
          </tr>
        <% end %>
        <% if @product.usage_type.present? %>
          <tr>
            <th>Tipo de uso</th>
            <td><%= @product.usage_type %></td>
          </tr>
        <% end %>
        <% if @product.gate_max_length.present? %>
          <tr>
            <th>Largo máximo de portón</th>
            <td><%= "#{@product.gate_max_length} metros" %></td>
          </tr>
        <% end %>
        <% if @product.warranty.present? %>
          <tr>
            <th>Garantía</th>
            <td><%= @product.warranty %></td>
          </tr>
        <% end %>
        <% if @product.arms.present? %>
          <tr>
            <th>Brazos</th>
            <td><%= @product.arms %> brazos</td>
          </tr>
        <% end %>
        <% if @product.accionamiento.present? %>
          <tr>
            <th>Accionamiento</th>
            <td><%= @product.accionamiento %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <p class="text-muted text-center">
    <%= @product.warranty_description %>
  </p>

  <!-- Productos relacionados -->
  <h2 class="mt-5">Productos Relacionados</h2>
  <div class="row row-cols-2 row-cols-md-3 row-cols-lg-5 g-4">
    <% @related_products.each do |related_product| %>
      <div class="col">
        <div class="card productcard h-100">
          <% if related_product.photos.present? %>
            <%= link_to product_path(related_product) do %>
              <%= cl_image_tag(related_product.photos.first.key, class: "card-img-top p-3", height: 200, width: 180, crop: :fill, alt: related_product.name) %>
            <% end %>
          <% end %>
          <div class="card-body d-flex flex-column">
            <h5 class="card-title"><%= link_to related_product.name, related_product %></h5>
            <div class="mt-auto">
              <% if related_product.on_sale? %>
                <p class="card-text text-decoration-line-through text-muted">$<%= related_product.formatted_price %></p>
                <p class="card-text">$<%= related_product.formatted_promotional_price %></p>
              <% else %>
                <p class="card-text">$<%= related_product.formatted_price %></p>
              <% end %>
              <%= button_to cart_items_path(product_id: related_product.id, quantity: 1), method: :post, class: "btn btn-custom btn-primary" do %>
                <i class="fa-solid fa-cart-plus"></i> Agregar
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%# ok %>

<script>
  document.addEventListener('turbo:load', function () {
    const decrementButton = document.getElementById('button-decrement');
    const incrementButton = document.getElementById('button-increment');
    const quantityInput = document.getElementById('quantity-input');

    if (decrementButton && incrementButton && quantityInput) {
      // Decrementar cantidad
      decrementButton.addEventListener('click', function () {
        let currentValue = parseInt(quantityInput.value);
        const min = parseInt(quantityInput.getAttribute('min')) || 1;
        if (currentValue > min) {
          quantityInput.value = currentValue - 1;
        }
      });

      // Incrementar cantidad
      incrementButton.addEventListener('click', function () {
        let currentValue = parseInt(quantityInput.value);
        const max = parseInt(quantityInput.getAttribute('max')) || Infinity;
        if (currentValue < max) {
          quantityInput.value = currentValue + 1;
        }
      });

      // Actualizar el valor en el botón de "Agregar al Carrito"
      const addToCartButton = document.querySelector('form[action*="cart_items"]');
      if (addToCartButton) {
        addToCartButton.addEventListener('submit', function (event) {
          const quantityField = document.createElement('input');
          quantityField.type = 'hidden';
          quantityField.name = 'quantity';
          quantityField.value = quantityInput.value;
          addToCartButton.appendChild(quantityField);
        });
      }
    }
  });
</script>

<%# ok %>

app/views/products/update.html.erb
<h1>Products#update</h1>
<p>Find me in app/views/products/update.html.erb</p>